spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/adoptme_api
        username: root
        password: 1234
    servlet:
        multipart:
            max-file-size: 10MB
            max-request-size: 10MB
upload:
    path: api/src/main/resources/static
api:
    security:
        token:
            secret: animais
